### ISSUE TITLE
Moken Request for Comment - MIP 5, What is a NuKey?

### ISSUE THREAD

**Issue by tobiyahtafari** [Mokens/MIPs#5]
### **What is a NuKey?**

NuKeys are [Mokens ](https://github.com/Mokens/MIPs/blob/master/MIPS/mip-2-Goals-and-Objectives.md) that are [ERC721](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-721.md) compliant and [ERC998](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-998.md) compliant non-fungible tokens minted on the main Ethereum network from the [Mokens contract](https://mokens.io/about/mokens-contract). NuKeys are essentially the first crypto-collectible that is built on top of the Mokens infrastructure. 

The general purpose of NuKeys are to provide the ERC20 token [NuMoney](https://etherscan.io/token/0x9ee57f885cdb20b34b2109d09cf8d3a41466cb9d) unique NuKey Moken minting permissions and to provide restricted website access for NuKey Moken holders. NuKeys will also act as raffle tickets towards NuMoney raffle giveaways.

### **Moken Type**

Traditionally there are only one type of Mokens that can currently be minted via the [official Mokens Website](https://mokens.io). We propose to add "Moken" type as a standard attribute to Mokens to further distinction of future Mokens to be created with special attributes.

NuKey will be one of the first types of Mokens other than the original/traditional Mokens.

### **Minting A NuKey**

The Process of minting a NuKey is similar to that of minting a traditional Moken. There are few differences. NuKey Mokens have distinct attributes attached to them.

NOTE: Possession of any NuKey types grants restricted access to Legal Documentation page on the official NuKey website.

- **NuKey ID**: NuKey IDs are automatically and sequentially generated within the Moken Name field. Each time a new NuKey Moken is minted a new NuKey Moken ID is created and associated with the NuKey Moken. A NuKey Moken id is a numeric identifier for a NuKey. They are created sequentially starting from 0. You will see them as NuKey 0, NuKey 1, NuKey 2, NuKey 3 etc. Each NuKey ID can have the attribute of NuKey Type: Bronze, Silver, or Gold. 

- **NuKey Moken Name**: Traditional Mokens have custom names. NuKey IDs are automatically and sequentially generated within the Moken Name. NuKey Moken Name and NuKey IDs are synonymous with one another.

- **NuKey Moken Description**: NuKey Moken Descriptions are all the same and automatically generated in the place of Moken Description. All NuKey Moken Descriptions will have "NuKey Type" autofilled within the field.

- **NuKey Type**: NuKey type should not be confused with Moken Type. There are 3 types of NuKeys. Bronze, Silver & Gold are the 3 types. Each type can be minted based upon the amount of [NuMoney](https://etherscan.io/token/0x9ee57f885cdb20b34b2109d09cf8d3a41466cb9d) ERC20 tokens present within the users wallet.
1. Bronze: Must have 1 - 99 NuMoney Tokens for minting permission.
2. Silver: Must have 100 - 999 NuMoney Tokens for minting permission.
3. Gold: Must have 1000 or more NuMoney Tokens for minting permission.

- **NuKey Moken Tags**: NuKey Mokens will have 3 specific tags attached. All NuKeys will have the tag "NuKey" and "NuMoney". Depending on what kind of NuKey Moken is minted, the third tag will be either "Bronze", "Silver" or "Gold".

- **Moken ID**: NuKey will be minted within the infrastructure of Mokens. The first NuKey will still be a continuation of the pre-existing Mokens.

- **NuKey Image**: There are only 3 images that coincide with each NuKey Type and are associated with 3 pre-generated images. 
1. Bronze Coincides with: [https://prickly-bell5487.on.getshifter.io/wp-content/uploads/2018/11/NuKey-Bronze-768x768.png](https://prickly-bell5487.on.getshifter.io/wp-content/uploads/2018/11/NuKey-Bronze-768x768.png)
2. Silver Coincides with: [https://prickly-bell5487.on.getshifter.io/wp-content/uploads/2018/11/NuKey-Silver-768x768.png](https://prickly-bell5487.on.getshifter.io/wp-content/uploads/2018/11/NuKey-Silver-768x768.png)
3. Gold Coincides with: [https://prickly-bell5487.on.getshifter.io/wp-content/uploads/2018/11/NuKey-Gold-768x768.png](https://prickly-bell5487.on.getshifter.io/wp-content/uploads/2018/11/NuKey-Gold-768x768.png)

- **NuKey Era**: We propose for a NuKey Era February 1, 2019 - February 28, 2019. Otherwise, NuKeys can be minted during any Moken era and will abide with Moken mint price. Suggested NuKey Mint Price during NuKey Era is Free for first NuKey (not including gas fees). After that the mint price is 0.02 ETH.

**Comment by mudgen** [comment]
Looks good!

**Comment by tobiyahtafari** [comment]
A couple more additions were added. NuKey Era edit. NuKey Moken Name and Moken ID.

**Comment by tobiyahtafari** [comment]
More additions added. NuKey Moken Description and NuKey Tags.
