### ISSUE TITLE
New Era Proposal - Crypto Winter

### ISSUE THREAD

**Issue by mudgen** [Mokens/MIPs#6]
## Update
This proposal did not win. This one did: https://github.com/Mokens/MIPs/issues/7
```
Author: Nick Mudge <nick@mokens.io>
Era Name: Crypto Winter
Status: draft
Start Date: 1 March 2018
Mint Price: 1 ETH
```
Vote for this proposal by adding a supporting emoji to the bottom of this issue.

I propose that starting March 1st a new era begins, called Crypto Winter.

The mint price for this proposed era is 1 ETH. This new mint price is significantly higher than previous mint prices. The rational for this is given below.

### Low Cost Mokens Available on Open Sea

The Moken era "[Molder](https://github.com/Mokens/MIPs/issues/4)" (which means moken holder) runs from 1 October 2018 to 28 February 2019. This gives people time to create more free or low mint price mokens. Over 140 "Molder" mokens have been minted so far.

If someone does not want to pay the mint price of 1 ETH during the new moken era, then a person can still get a moken by purchasing an existing one at a low cost at OpenSea.io or through any ERC721 exchange.

### Eras Distinguish Sets of Mokens

The scarcity, price, quality and in the future the functionality of mokens are affected by which era they are part of. Mokens from one era are different than mokens from another era. 

Because the mint price is raised to 1 ETH it is expected that less mokens in the new era will be minted. This means the mokens of the new era will be more rare. 

The possibility is suggested that with the increased mint price the quality of mokens created may be higher, or the mokens may be more interesting.

### Funding the Development of Mokens

Money is needed to pay for the development of Mokens. The mint price fee pays for costs of development.

Definitely leave comments below to give suggestions about this era.

**If you disagree with this New Era Proposal then please write and submit your own New Era Proposal.** ***Anybody can write one.*** **You can also select negative emojis for this issue to show your disapproval. Otherwise please show your support with positive emojis.**

The process for determining a new era is here: https://github.com/Mokens/MIPs/blob/master/MIPS/mip-3-New-Era-Proposals.md

The last New Era Proposal that was accepted is here: https://github.com/Mokens/MIPs/issues/4

**If you want this proposed era to be selected for voting then please support it with supporting emojis.**

**Comment by abcoathup** [comment]
As per my Era proposal I believe a mint price of 1 ETH will see few if any more mokens minted.
