### ISSUE TITLE
New Era Proposal - #CryptoWinter

### ISSUE THREAD

**Issue by abcoathup** [Mokens/MIPs#7]
```
Author: Andrew B Coathup <@abcoathup everywhere>
Era Name: #CryptoWinter
Status: draft
Start Date: 1 March 2018
Mint Price: 0.001 ETH
```

I propose that starting March 1st a new era begins. Assuming hash tags can be used, it should be #CryptoWinter.

The mint price for the proposed new era is 0.001 ETH. This new mint price is significantly lower than previous mint prices and other new era proposals. The rationale for this is given below.

## Rationale
First, it's #CryptoWinter

Second, there are currently only 260 Mokens.  Mokens are not yet a thing, and may never be.  The number of Mokens needs to be heading towards 10,000 and beyond. (Think CryptoPunks)

Third, it really is #CryptoWinter, I think with a mint price of 1 ETH there would be few, if any (my prediction is 0) new mokens minted in the new era.

Fourth, we need the community to experiment, to create, to mint new mokens, not to effectively freeze minting.

Fifth, did I mention it's #CryptoWinter (I am going to keep repeating the name as I think it is great for the next new era)

### Funding the Development of Mokens
I fully appreciate that money is needed to pay for the development of Mokens. The mint price fee pays for costs of development.  A small mint price fee, even with 10,000 mokens does not fund much development, which means that there won't be new development until another era provides better funding or Mokens mint their own mokens for sale in the open market and use the profits from these to fund development.

Definitely leave comments below to give suggestions about this era.

**If you disagree with this New Era Proposal then please write and submit your own New Era Proposal.** _**Anybody can write one.**_ **You can also select negative emojis for this issue to show your disapproval. Otherwise please show your support with positive emojis.**

The process for determining a new era is here: https://github.com/Mokens/MIPs/blob/master/MIPS/mip-3-New-Era-Proposals.md

The last New Era Proposal that was accepted is here: #4

**If you want this proposed era to be selected for voting then please support it with supporting emojis.**

**Comment by mudgen** [comment]
I will be further developing Mokens whether I am paid or not.  The next functionality I plan to develop is the ability for molders to update the description, picture and tags of the mokens they own -- making mokens the first upgradeable cryptocollectibles.

**Comment by eyemine** [comment]
While I understand the rationale of making minting cost 1eth - meaning the digital asset somehow is then worth 1eth base. I agree with @abcoathup to encourage adoption and propagation the 0.001eth mint cost is  preferable. Though #cryptowinter strikes a chord,  it is quite bleak,  something more positive may resonate better. Here are a few #fineasset #pixlock #picert/#pixert

**Comment by abcoathup** [comment]
#CryptoWinter is intentionally bleak. 
It has had serious impact on people’s lives. 

Whilst spring might feel a way off, it is coming. 

But for now it is time to dig in deep and try to survive until then.

**Comment by abcoathup** [comment]
If mint price isn’t going to impact Nick’s current development plans, then I don’t see a need to effectively freeze minting with a price of 1 ETH.

**Comment by mudgen** [comment]
@abcoathup You and I and others are making mokens a thing. Thank you for making it a thing.

**Comment by zhangzhongnan928** [comment]
vote for this

**Comment by mudgen** [comment]
@abcoathup Besides a mint price change a new era can signal changes or new functionality for mokens. I have completed implementing the functionality that enables molders to upgrade their mokens. 

Specifically they can change the image, description and tags of their mokens. But this new functionality has not been released yet and I would like to release it at the start of the #CryptoWinter era. 

Can you add to your proposal that this new functionality will be released at the start of the #CryptoWinter era?

Mokens will be the world's first upgradeable cryptocollectibles.

**Comment by eyemine** [comment]
Hi,  I am intrigued.  A few questions.

Will there be a digital trail/evidence of upgrade?
So there are layers of versions? In my mind this is preferable.

Where does the thumbnail live?  Ipsf? Will that change too?

Isn't immutibility a property desirable for nft?

Who can upgrade moken, originator or holder? Private key holder I imagine.

Still think #cryptowinter is a bit of a downer

Regards

Angelo

**Comment by mudgen** [comment]
@eyemine Great questions!

> Will there be a digital trail/evidence of upgrade?

No

> So there are layers of versions?

No

> Where does the thumbnail live? Ipsf? Will that change too?

The images are stored on a centralized server, and the images and other moken data are available through the moken api: https://github.com/Mokens/MIPs/blob/master/MIPS/mip-4-Integrating-Mokens.md#moken-metadata

Of course the things that are stored in the Mokens contract, such as the moken name, moken id, moken era and ERC721 data are available from the Mokens contract on the Ethereum network.

> Isn't immutibility a property desirable for nft?

Absolutely. Mokens are a little different than other cryptocollectibles. Most cryptocollectibles focus on images as collectibles whereas mokens focus on ideas as collectibles as given in the name of a moken. The name of a moken, the moken id and the moken era do not change. The image, description and tags that are used to display and make a moken attractive can change. I think of these things like clothes. You are the same person every day but you can wear different clothes, or present yourself differently.

The idea of a moken that is given in its name does not change. And the names of mokens are unique.

>Who can upgrade moken, originator or holder? Private key holder I imagine.

The owner of a moken can upgrade the moken. Yes, this is the person who has the private key, and the private key is needed to make changes to a moken. This is done by signing a message with the private key to prove that the person is the owner of the address that owns a moken.

> Still think #cryptowinter is a bit of a downer

Yes. I would be happy if you made a New Era Proposal for 1 April 2019.  The name "believe" did well when I polled potential era names.

More info about mokens: https://mokens.io/about
